print("Sveika pasaule!")
print(2 * 2)
print(2 * 2, 2 * 3, 2 * 4, "Pitons")
print(f"Ja saskaitisim 5 un 7 tad bus {5+7}.")
print("Sveika, "+" pasaule") #komentars
print("Tomass")
print("Tomass")
print("Tomass")
print("Tomass")
print("Tomass")
print("Tomass")
print("Tomass "*7)
print("Tulin beigas")